# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('closetId', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'closets',
            },
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('outfitId', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'outfits',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.IntegerField(primary_key=True, serialize=False)),
                ('productName', models.TextField()),
                ('brand', models.TextField()),
                ('color', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imgUrl', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('typeName', models.TextField(primary_key=True, serialize=False)),
                ('parentType', models.CharField(max_length=20)),
                ('season', models.CharField(max_length=20)),
                ('occasion', models.CharField(max_length=30)),
            ],
            options={
                'managed': False,
                'db_table': 'types',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('fName', models.TextField()),
                ('lName', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'users',
            },
        ),
    ]
